version: '3.3'
services:
    php-fpm:
        image: gpupo/container-orchestration:php-dev
        volumes:
            - $PWD/:/var/www/app
    mariadb:
        image: mariadb
        restart: always
        expose:
          - 3306
        environment:
          MYSQL_ROOT_PASSWORD: mas7er
          MYSQL_USER: app_db_user
          MYSQL_PASSWORD: app8as3
          MYSQL_DATABASE: app
